#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "eric-esoa-dr.name" . }}-rest-service-rbac-configmap
  labels:
    app: {{ template "eric-esoa-dr.name" . }}
  {{- include "eric-esoa-dr.kubernetes-io-info" .| nindent 4 }}
    com.ericsson.bss/bam-global-rbac: {{ .Values.rbac.label }}
  annotations:
  {{- include "eric-esoa-dr.annotations" .| nindent 4 }}
data:
  rbac: |
    policy:
      rest-service-reader-1:
        PType: p
        V0: eric-bos-dr:reader
        V1: /rest-service/v1/resource-configurations*
        V2: get
      rest-service-writer-1:
        PType: p
        V0: eric-bos-dr:writer
        V1: /rest-service/v1/resource-configurations*
        V2: get
      rest-service-writer-2:
        PType: p
        V0: eric-bos-dr:writer
        V1: /rest-service/v1/resource-configurations*
        V2: create
      rest-service-writer-3:
        PType: p
        V0: eric-bos-dr:writer
        V1: /rest-service/v1/resource-configurations*
        V2: update
      rest-service-writer-4:
        PType: p
        V0: eric-bos-dr:writer
        V1: /rest-service/v1/resource-configurations*
        V2: delete
      rest-service-writer-5:
        PType: p
        V0: eric-bos-dr:writer
        V1: /rest-service/v1/run*
        V2: create
      rest-service-admin-1:
        PType: p
        V0: eric-bos-dr:admin
        V1: /rest-service/v1/resource-configurations*
        V2: get
      rest-service-admin-2:
        PType: p
        V0: eric-bos-dr:admin
        V1: /rest-service/v1/resource-configurations*
        V2: create
      rest-service-admin-3:
        PType: p
        V0: eric-bos-dr:admin
        V1: /rest-service/v1/resource-configurations*
        V2: update
      rest-service-admin-4:
        PType: p
        V0: eric-bos-dr:admin
        V1: /rest-service/v1/resource-configurations*
        V2: delete
      rest-service-admin-5:
        PType: p
        V0: eric-bos-dr:admin
        V1: /rest-service/v1/run*
        V2: create
