#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#
{{- if and .Values.tags.standalone .Values.global.hosts.iam }}
{{ $authnClientSecret := lookup "v1" "Secret" .Release.Namespace .Values.global.iam.kubernetesSecret }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "eric-esoa-dr.name" . }}-authn-proxy-client-configmap
  labels:
    app: {{ template "eric-esoa-dr.name" . }}
  {{- include "eric-esoa-dr.kubernetes-io-info" .| nindent 4 }}
    com.ericsson.bss/bam-global-rbac: {{ .Values.rbac.label }}
  annotations:
  {{- include "eric-esoa-dr.annotations" .| nindent 4 }}
data:
  client-configuration.json: |-
    {
      "clientId": "authn-proxy",
      "enabled": true,
      "attributes": {
        "access.token.lifespan": "900"
       },
      "redirectUris": [ "https://*", "http://*" ],
{{- if $authnClientSecret }}
      "secret": "{{ (index $authnClientSecret "data" .Values.global.iam.secretKey) | b64dec }}",
{{- end }}
      "protocol": "openid-connect",
      "publicClient": "false",
      "defaultClientScopes": [
        "web-origins",
        "dr-role-mapper",
        "role_list",
        "profile",
        "roles",
        "email"
      ],
      "optionalClientScopes": [
        "address",
        "phone",
        "offline_access",
        "microprofile-jwt"
      ],
      "protocolMappers": [
        {
          "protocolMapper": "oidc-hardcoded-claim-mapper",
          "protocol": "openid-connect",
          "name": "aud-AuthorizationClient-mapper",
          "config": {
            "claim.type": "String",
            "claim.name": "aud",
            "claim.value": "AuthorizationClient",
            "id.token.claim": "true",
            "access.token.claim": "true"
          }
        }
      ]
    }
{{- end }}