#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ $authnClientSecret := (lookup "v1" "Secret" .Release.Namespace .Values.global.iam.kubernetesSecret) }}
{{- if and .Values.tags.standalone (not $authnClientSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.iam.kubernetesSecret }}
  labels:
    {{- include "eric-esoa-dr.labels" .| nindent 4 }}
  annotations:
    {{- include "eric-esoa-dr.annotations" .| nindent 4 }}
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
{{ printf "%s: %s" .Values.global.iam.secretKey (randAlphaNum 33 | b64enc) | indent 2 }}
{{- end }}
