#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ template "eric-esoa-dr.ingressClass" . }}
  name: eric-esoa-dr-service
spec:
  routes:
  - conditions:
    - prefix: /discovery-and-reconciliation
    services:
    {{- if .Values.ingress.rbac.enabled}}
    - name: eric-esoa-dr-service-rbac-proxy
      port: 9443
      protocol: tls
      {{- if .Values.global.security.tls.enabled }}
      validation:
        caSecret: {{ .Values.ingress.tls.caSecret }}
        subjectName: eric-esoa-dr-service-rbac-proxy
      {{- end }}
    timeoutPolicy:
      response: "300s"
    rateLimitPolicy:
    {{- toYaml .Values.ingress.rateLimitPolicy | nindent 6 }}
    {{ else }}
    - name: eric-esoa-dr-service
      port: 80
    {{- end }}
