#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if .Values.global.hosts.iam }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-esoa-dr.name" . }}-iam-groups-configmap
  labels:
    app: {{ template "eric-esoa-dr.name" . }}
  {{- include "eric-esoa-dr.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-esoa-dr.annotations" .| nindent 4 }}
data:
  groups.json: |
    [{"name": "eric-bos-dr:writer"}, {"name": "eric-bos-dr:reader"}, {"name": "eric-bos-dr:admin"}, {"name": "ESOA_SubsystemViewer"}, {"name": "ESOA_SubsystemAdmin"}]
{{- end }}