#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}:{{ template "eric-esoa-dr.name" . }}-rbac-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}:{{ template "eric-esoa-dr.name" . }}-rbac-proxy
subjects:
  - kind: ServiceAccount
    name: eric-esoa-dr-service-rbac-proxy
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: eric-esoa-rest-service-rbac-proxy
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: eric-esoa-dr-ui-rbac-proxy
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: eric-esoa-subsystem-management-rbac-proxy
    namespace: {{ .Release.Namespace }}